import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Form from '@/Components/Form'
import Footer from '@/Components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Login • Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Instagram_logo_2016.svg.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Form/>
      </main>
      <Footer/>
    </>
  )
}
